# Generated by Django 6.0.3 on 2026-04-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_availability_user_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_id',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
