# Generated by Django 6.0.3 on 2026-04-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_display_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_id',
            field=models.CharField(blank=True, default='', max_length=10, unique=True),
        ),
    ]
