# Generated by Django 6.0.3 on 2026-04-19 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_display_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentorassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mentorassignment',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentorassignment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='core.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorassignment',
            unique_together={('mentor', 'learner', 'subject')},
        ),
    ]
