# Generated by Django 6.0.3 on 2026-04-20 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mentorrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='school',
        ),
    ]
